version: '3.8'

services:
  node1:
    build: .
    environment:
      - NODE_ID=node1
      - HTTP_PORT=8081
      - GRPC_PORT=9091
      - PEERS=node2:9092,node3:9093
    ports:
      - "8081:8081"
      - "9091:9091"

  node2:
    build: .
    environment:
      - NODE_ID=node2
      - HTTP_PORT=8082
      - GRPC_PORT=9092
      - PEERS=node1:9091,node3:9093
    ports:
      - "8082:8082"
      - "9092:9092"

  node3:
    build: .
    environment:
      - NODE_ID=node3
      - HTTP_PORT=8083
      - GRPC_PORT=9093
      - PEERS=node1:9091,node2:9092
    ports:
      - "8083:8083"
      - "9093:9093"
